export default function TermsPage() {
  return (
    <article className="prose prose-invert mx-auto max-w-3xl">
      <h1 className="font-display text-4xl font-bold">Terms of Service</h1>
      <p className="text-sm text-muted">Last updated: 2026.</p>

      <h2 className="mt-6 font-display text-2xl">1. Be excellent to each other</h2>
      <p className="text-muted">
        RoastGPT generates comedic insults at the named user. Don&apos;t use it to harass, dox, or
        threaten real people. The roasts are AI-generated entertainment, not factual statements.
      </p>

      <h2 className="mt-6 font-display text-2xl">2. Refunds</h2>
      <p className="text-muted">
        Paid plans are billed once for the stated duration (e.g. ₹299 for 10 days). If a paid
        feature is broken for more than 48 hours after you report it, contact
        <a className="text-accent-3" href="mailto:support@roastgpt.app">support@roastgpt.app</a>
        for a prorated refund.
      </p>

      <h2 className="mt-6 font-display text-2xl">3. No warranty</h2>
      <p className="text-muted">
        The service is provided as-is. Roasts are generated by software and may be inaccurate,
        offensive, or accidentally on point. You agree not to hold us liable for emotional damage,
        real or performed.
      </p>

      <h2 className="mt-6 font-display text-2xl">4. Account termination</h2>
      <p className="text-muted">
        We reserve the right to suspend accounts that abuse the service (credential stuffing,
        payment fraud, automated scraping). Suspended accounts lose access to paid features with
        no refund.
      </p>

      <h2 className="mt-6 font-display text-2xl">5. Changes</h2>
      <p className="text-muted">
        We may update these terms. The &quot;last updated&quot; date at the top will reflect the
        change. Continued use of the service after a change constitutes acceptance.
      </p>
    </article>
  );
}
